(function() {

  window._memberships = [{
    PersonId: 1,
    From: '2017-01-01',
    To: '2017-12-31',
    Name: 'Gym access',
    FirstName: 'Emilia',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/emilia.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal",
    OrganizationAddress: "1000 Ave Émile-Journault, Montréal, QC, H2M 2E7, CA",
    OrganizationPhone: "(514) 872-7177",
    OrganizationEmail: "info@sportsmontreal.com",
    OrganizationWebsite: "www.sportsmontreal.com"
  }, {
    PersonId: 2,
    From: '2017-01-01',
    To: '2017-12-31',
    Name: 'ADULTE Member 2016 /JEANNE-MANCE (résident)',
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 101,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal",
    OrganizationAddress: "285, rue Gary-Carter, bur. 202, Montréal, QC, H2R 2W1, CA",
    OrganizationPhone: "(514) 872-7177",
    OrganizationEmail: "info@tennismontreal.qc.ca",
    OrganizationWebsite: "www.tennismontreal.qc.ca"
  }, {
    PersonId: 3,
    From: '2017-01-01',
    To: '2017-08-31',
    Name: 'Gym access',
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal",
    OrganizationAddress: "1000 Ave Émile-Journault, Montréal, QC, H2M 2E7, CA",
    OrganizationPhone: "(514) 872-7177",
    OrganizationEmail: "info@sportsmontreal.com",
    OrganizationWebsite: "www.sportsmontreal.com"
  }, {
    PersonId: 4,
    From: '2017-01-01',
    To: '2017-12-31',
    Name: 'JUNIOR Member 2016 Claude-Robillard (résident)',
    FirstName: 'Eloi',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/eloi.jpg',
    OrganizationId: 101,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal",
    OrganizationAddress: "285, rue Gary-Carter, bur. 202, Montréal, QC, H2R 2W1, CA",
    OrganizationPhone: "(514) 872-7177",
    OrganizationEmail: "info@tennismontreal.qc.ca",
    OrganizationWebsite: "www.tennismontreal.qc.ca"
  }, {
    PersonId: 1,
    From: '2015-09-01',
    To: '2016-08-31',
    Name: 'Registered member',
    FirstName: 'Emilia',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/emilia.jpg',
    OrganizationId: 501,
    OrganizationLogoUrl: 'img/skate-canada.png',
    OrganizationName: "Skate Canada",
    OrganizationAddress: "261 – 1200 St. Laurent Blvd., Ottawa, ON, K1K 3B8",
    OrganizationPhone: "(613) 747-1007",
    OrganizationEmail: "info@skatecanada.ca",
    OrganizationWebsite: "skatecanada.ca"
  }];

  window._purchases = [{
    Id: 1000,
    Name: 'Camp option floor hockey - Floor hockey, 7-8 years old - Week 7 : August 8 to 12 2016',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 3,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1001,
    Name: "Power yoga - Spring 2016",
    Type: 'Activity',
    InvoiceId: 2001,
    PersonId: 1,
    FirstName: 'Emilia',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/emilia.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1002,
    Name: "Multisport camp - Champions club (7-8 years old) - Wekk 2 : July 4 to 8 2016",
    Type: 'Activity',
    InvoiceId: 2002,
    PersonId: 4,
    FirstName: 'Eloi',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/eloi.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1003,
    Name: "Rec league (doubles) Tuesday, Lvl. 3.5/4.0 - 19PM to 21PM - From May 21 to Sept 3 2016.",
    Type: 'Activity',
    InvoiceId: 2003,
    PersonId: 4,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }, {
    Id: 1004,
    Name: "Adult membership 2016 (resident) Tennis  Montréal/Jeanne-Mance",
    Type: 'Membership',
    InvoiceId: 2004,
    PersonId: 2,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }, {
    Id: 1005,
    Name: "Adulte membership 2016 (resident) Tennis  Montréal/Jeanne-Mance",
    Type: 'Membership',
    InvoiceId: 2005,
    PersonId: 4,
    FirstName: 'Eloi',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/eloi.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }];

  window._events = [{
    Id: 1000,
    When: '2016-08-08 09:00:00',
    Start: ' 9:00',
    End: '16:00',
    DateString: 'Monday August 8',
    Name: 'Floor hockey camp',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 3,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1001,
    When: '2016-08-09 09:00:00',
    Start: ' 9:00',
    End: '16:00',
    DateString: 'Tuesday August 9',
    Name: 'Floor hockey camp',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 3,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1002,
    When: '2016-08-09 19:00:00',
    Start: '19:00',
    End: '21:00',
    DateString: 'Tuesday August 9',
    Name: "Rec league (doubles) Tuesday, Lvl. 3.5/4.0 - 19PM to 21PM",
    Type: 'Activity',
    InvoiceId: 2003,
    PersonId: 4,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }, {
    Id: 1003,
    When: '2016-08-10 09:00:00',
    Start: ' 9:00',
    End: '16:00',
    DateString: 'Wednesday August 10',
    Name: 'Floor hockey camp',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 3,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1004,
    When: '2016-08-11 09:00:00',
    Start: ' 9:00',
    End: '16:00',
    DateString: 'Thursday August 11',
    Name: 'Floor hockey camp',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 3,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1005,
    When: '2016-08-12 09:00:00',
    Start: ' 9:00',
    End: '16:00',
    DateString: 'Friday August 12',
    Name: 'Floor hockey camp',
    Type: 'Activity',
    InvoiceId: 2000,
    PersonId: 3,
    FirstName: 'Ludovic',
    LastName: 'Bazinet',
    ProfilePictureUrl: 'img/ludovic.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1006,
    When: '2016-08-16 19:00:00',
    Start: '19:00',
    End: '21:00',
    DateString: 'Tuesday August 16',
    Name: "Rec league (doubles) Tuesday, Lvl. 3.5/4.0 - 19PM to 21PM",
    Type: 'Activity',
    InvoiceId: 2003,
    PersonId: 4,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }, {
    Id: 1007,
    When: '2016-08-23 19:00:00',
    Start: '19:00',
    End: '21:00',
    DateString: 'Tuesday August 23',
    Name: "Rec league (doubles) Tuesday, Lvl. 3.5/4.0 - 19PM to 21PM",
    Type: 'Activity',
    InvoiceId: 2003,
    PersonId: 4,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }, {
    Id: 1008,
    When: '2016-08-30 19:00:00',
    Start: '19:00',
    End: '21:00',
    DateString: 'Tuesday August 30',
    Name: "Rec league (doubles) Tuesday, Lvl. 3.5/4.0 - 19PM to 21PM",
    Type: 'Activity',
    InvoiceId: 2003,
    PersonId: 4,
    FirstName: 'Martin',
    LastName: 'Drapeau',
    ProfilePictureUrl: 'img/martin.jpg',
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/tennis-montreal.png',
    OrganizationName: "Tennis Montréal"
  }];

  window._communications = [{
    Id: 1000,
    Status: 'Unread',
    When: '2016-08-06',
    From: 'Seb Goal',
    Subject: "Camp option hockey cosom",
    Body: "Bonjour Ludovic,<br/>Voici la liste des choses à apporter:<br/><ul><li>bouteille d'eau</li><li>bâton</li><li>protèges tibias</li></ul>",
    InvoiceId: 2003,
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1001,
    Status: 'Read',
    When: '2016-08-01',
    From: 'Julie Yoga',
    Subject: "Power yoga - mercredi 20 mai, cours annulé",
    Body: "Le cours de ce soir a été annulé. Il sera repris à la fin de la session.",
    InvoiceId: 2003,
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }, {
    Id: 1002,
    Status: 'Read',
    When: '2016-06-30',
    From: 'Rafa Nadal',
    Subject: "LIGUE RÉCRÉATIVE (jeu en double) Mardi, Niv. 3.5/4.0 - 19h00 à 21h00",
    Body: "Bienvenu au cours que je vais donner. J'ai pris ma retraite professionnelle justement pour vous!",
    InvoiceId: 2003,
    OrganizationId: 201,
    OrganizationLogoUrl: 'img/sports-montreal.jpg',
    OrganizationName: "Sports Montréal"
  }];

}.call(this));